# Generated by Django 4.2.1 on 2023-07-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='ce0_desc',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='ceo_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='desc2',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='desc3',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='ceo_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
